### ISSUE TITLE
Save volume state

### ISSUE THREAD

**Issue by FabricioCabeca** [MycroftAI/skill-naptime#10]
After a nap Mycroft should be able to restore the previous volume state.

Steps to reproduce:
1 - Say "hey... set volume to 10" 
2 - Say "hey... go to sleep"
3 - Say "hey... wake up"
4 - Say "hey... raise volume"
>> Volume increased to 7

Expected result:
>> Volume increased to 11

**Comment by krisgesling** [comment]
Hi there, thanks for reporting this. 

I just did a quick test and this seems to have been fixed at some point.
