### ISSUE TITLE
Naptime mutes entire system

### ISSUE THREAD

**Issue by chowbok** [MycroftAI/skill-naptime#3]
Maybe this is just a problem with my setup, but when I tell Mycroft to go to sleep, it mutes everything on the system, not just Mycroft-related sounds. Can this be changed, or made configurable?

**Comment by roadriverrail** [comment]
This is impacting me, too.  I use Mycroft on my workstation and use the naptime skill to turn off Mycroft during meetings.  Not only does it mute the sound, but it also doesn't respond to the wakeup command any longer.

**Comment by penrods** [comment]
Just checking are you both working on Linux desktop/laptop installs?  That skill was originally designed with the Mark 1 case in mind, so yes it does mute all system sounds.  But that could become an option.

As for the "wakeup comand not working any longer", can you give me more details?  When did it last work?  What (exactly) do you say to try and wake it back up?

**Comment by chowbok** [comment]
I am on a Linux desktop, yes. I'm not seeing the behavior roadriverrail is seeing, however; mine still wakes up.

**Comment by roadriverrail** [comment]
Yep, this is for a desktop install.  I realize we're a little bit "out of
bounds" compared to the Mark 1, but IIRC, I'm registered with the Mycroft
backend as a desktop, so maybe you can use that to power a conditional?

I tried this 2-3 times, and after putting Mycroft to sleep, "Hey Mycroft,
wake up" doesn't appear to do anything.  I get the chirp for "Hey Mycroft",
but the wake command doesn't have any effect and I end up restarting my
Mycroft instance to fix it.

Best,
Rhett

**Comment by krisgesling** [comment]
Looks like #4 addresses this. Thanks again for the fix :)
