### ISSUE TITLE
Schedule a naptime and wakeup time

### ISSUE THREAD

**Issue by pfefferle** [MycroftAI/skill-naptime#40]
I would love to schedule time, where mycroft goes to sleep and wakes up, so mycroft goes to sleep when I do for example :)

**Comment by krisgesling** [comment]
Yeah nice idea!

This would make a great hacktoberfest project too :)

**Comment by hariedo** [comment]
I would also recommend a default configurable time span for the generic "go to sleep."  For example, if nonzero, sleep for 3 hours.  This helps to fend off false detections during a movie or party where Mycroft is not invited.
