### ISSUE TITLE
Mycroft Mark II screen does not reflect the "gone to sleep" status.

### ISSUE THREAD

**Issue by hariedo** [MycroftAI/skill-naptime#42]
After specifying "Mycroft, go to sleep", the naptime skill suppresses most voice interaction until unlocked with one phrase, "Mycroft, wake up."  There is no visual indication on Mark II screen, even though there seems to be a "face" directory.  Thus, family members who didn't know it was put to sleep may be frustrated by lack of response.

If Naptime is a sovereign modal skill (blocking out all other skills from running), it needs to display something on the screen (or go fully black with a gentle breathing white LED pattern).  If Naptime is not sovereign, then the idle homescreen needs to be informed, and should do this visual work instead.

**Environment (please complete the following information):**
 - Device type: Mark II
 - OS: Mark II
 - Mycroft-core version: 2021-12-13
 - Other versions: 2021-12-13

**Comment by krisgesling** [comment]
Hey, there is a sleeping face that should be displayed anytime the device is "put to sleep".

Do you see the sleep or wake faces at all? Being did they show and then disappear, or do you not see them at all?

The face directory you mentioned - did you see that on your device or only in this repo? I'm wondering if your device hasn't updated to the latest version of the Naptime Skill properly.

Can you run:
```
cd /opt/mycroft/skills/mycroft-naptime.mycroftai/
git status
```

If you think it is out dated you can get the latest version by running: 
```
git checkout 21.02
git pull
```

**Comment by hariedo** [comment]
It's on branch 21.02, but was nine commits behind head.  After a git pull, it now has a face, which addresses the original issue I posted. But no clock, which I think is a step backwards in usefulness.
