### ISSUE TITLE
Naptime skill should respond and consume command to "wake up" even if already awake

### ISSUE THREAD

**Issue by hariedo** [MycroftAI/skill-naptime#43]
If you trigger the Naptime skill by saying "go to sleep", the Naptime skill will be in a napping state, and will then listen ONLY for the special phrase "wake up" from that point forward.

If you are not sure whether Mycroft is functioning correctly, you may try "wake up" just in case it is in a napping state.  In the case that Naptime is active, "wake up" will properly return Mycroft to a wakeful state and listen for any/all commands once again.

**In the case that Naptime is NOT active, then "wake up" will be mis-interpreted** by some other fallback skill.  For example, DuckDuckGo may decide you intended to learn something about the 2009 movie, Wake Up Sid.  There is virtually no situation where "wake up" will be useful for any other intent.

Proposed:  when wakeful, Naptime should recognize and consume "wake up".  It can reply briefly, "I am already awake" but should not allow the command to fall back to some other skill.

**Comment by krisgesling** [comment]
Hey Ed - good suggestion - I've made a PR for this.

If you have a chance to test it out and confirm it's working as expected we can merge it in :)
