### ISSUE TITLE
No way to wake up without button

### ISSUE THREAD

**Issue by nielstron** [MycroftAI/skill-naptime#5]
As there is no keyword for any wake up call, it is improbable that mycroft will "wake up" again by words after having gone to bed.

**Comment by penrods** [comment]
It can be verbally brought back by saying "Hey Mycroft, wake up".  This generates a ```mycroft.awoken``` message that is handled by the handle_awoken() method.
https://github.com/MycroftAI/skill-naptime/blob/master/__init__.py#L32

Inside mycroft-core this ```mycroft.awoken``` message gets generated by the "wakeup_recognizer" on the inner "listener" bus:
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/listener.py#L238
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/listener.py#L117

Then forwarded to the main messagebus:
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/main.py#L49

**Comment by penrods** [comment]
Unless you disagree, I'm going to go ahead and close out this issue @nielstron

**Comment by nielstron** [comment]
Yes that sounds reasonable, thanks for clarifying!                                                                                                                                                                                                                                                                                                                From: notifications@github.comSent: January 5, 2018 22:23To: skill-naptime@noreply.github.comReply-to: reply@reply.github.comCc: n.muendler@web.de; mention@noreply.github.comSubject: Re: [MycroftAI/skill-naptime] No way to wake up without button (#5)  Unless you disagree, I'm going to go ahead and close out this issue @nielstron

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
