### ISSUE TITLE
The vocal reminder how to wake up reflects default wake phrase.

### ISSUE THREAD

**Issue by hariedo** [MycroftAI/skill-naptime#8]
If the user has specified "yo, tambourine man" as the wake phrase, then the vocal reminder on sleeping should reflect it:  "Say yo, tambourine man, wake up to get my attention".  The configurable wake word has a plaintext as well as a phoneme set, so you should be able to fetch that setting.

**Comment by krisgesling** [comment]
Looks like this got addressed already. Closing.
